[package]
name = "YETII"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "8.0.0"
serde_yaml = "0.9.34+deprecated"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.37", features = ["derive"] }
serde_json = "1.0.140"
once_cell = "1.21.3"
